### ISSUE TITLE
Automate publishing releases

### ISSUE THREAD

**Issue by MarkKoz** [Sigvaard/dotnet-license#6]
I'd like to use this tool as a CI step in my projects but the package is outdated on NuGet and build artifacts are too old and have been deleted. Building it myself doesn't look like a great option. Are there any plans to automate publishing releases, or at the least, manually publish a pre-release?

**Comment by bugproof** [comment]
Hello @MarkKoz , first of all sorry for a late reply. Do you mean automated publishing on nuget or here on github? I will try to take care of it soon.

**Comment by MarkKoz** [comment]
I meant automatically publishing a nuget package to a nuget repository like nuget.org. This will make installation of the latest version of the tool easy since the command can fetch from remote nuget repos like nuget.org. 

At the least, the package from the build artefacts in CI could be auto published on nuget.org as a pre-release. You could also have full releases automatically triggered when you bump the version or push a git tag.

**Comment by bugproof** [comment]
After 1 year but it's done 😄
I fixed some bugs too because for some reason it stopped working with .NET standard and .NET 5 projects...
