### ISSUE TITLE
Make it faster!

### ISSUE THREAD

**Issue by scabana** [Sigvaard/dotnet-license#9]
Hello!

First of all, thanks for the tool!

It can get quite long to run the tool, tried to parallelize the `foreach` here: https://github.com/bugproof/DotnetThirdPartyNotices/blob/47a81cdcb8f9f7e8028ed2e9c69a4bda4fa43ba6/src/DotnetThirdPartyNotices/Program.cs#L72-L97 and got from 43 to less than 5 seconds to run the tool. The only challenge is to output grouped logs, I could come up with something. Would you be willing to accept a PR for this?

**Comment by bugproof** [comment]
PRs are welcome. I rarely use the tool so this performance is acceptable to me.
